version: '3'
services:
  wechat-chatgpt:
    image: warpspeed/wechat-chatgpt:v1.0
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./logs:/code/logs
      - ./memory:/code/memory
    restart: always
